name: Format check on pull request
on: pull_request
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Format
        run: |
          echo "::set-env name=PATH::${PATH}:${HOME}/.dotnet/tools"
          dotnet tool install -g dotnet-format

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-changed-files: "true"

      - name: Debug details
        if: failure()
        shell: pwsh
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo ${env:PATH}
