name: Format check on pull request
on: pull_request
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-changed-files: "true"

      - name: Debug details
        if: failure()
        shell: pwsh
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          Get-Location
          echo ${env:PATH}
          echo ${{ secrets.GITHUB_TOKEN }}
          echo $env:INTERNAL_VARIABLE
          echo ${env:buildConfiguration}
          echo ${{github.actor}}
          echo https://github.com/${{github.repository}}/workflows/${{github.workflow}}/badge.svg
          echo 1-${env:buildNumber}
          echo 2-$env:buildNumber
          echo 3-${buildNumber}
          echo 4-$buildNumber
          echo "This workflow run is triggered by ${{ github.event_name }} ."
          echo "*****************************************************************************"
          echo "$env:GITHUB_CONTEXT"
          echo "*****************************************************************************"
